{% set version = '1.1-6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tsp
  version: {{ version|replace("-", "_") }}

source:
  fn: TSP_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/TSP_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TSP/TSP_{{ version }}.tar.gz
  sha256: 8cc2793995cf475ae0d9a15c48c059cb009ec48b1c4416f37457b228683fa9fa

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-foreach
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-foreach

test:
  commands:
    - $R -e "library('TSP')"           # [not win]
    - "\"%R%\" -e \"library('TSP')\""  # [win]

about:
  home: http://lyle.smu.edu/IDA/seriation
  license: GPL-3
  summary: Basic infrastructure and some algorithms for the traveling salesperson problem (also
    traveling salesman problem; TSP). The package provides some simple algorithms and
    an interface to the Concorde TSP solver and its implementation of the Chained-Lin-Kernighan
    heuristic. The code for Concorde itself is not included in the package and has to
    be obtained separately.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
