{% set version = "1.2-4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tsp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TSP_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TSP/TSP_{{ version }}.tar.gz
  sha256: 30bd0bfe9a7ca3fdf4f91c131f251e2835640f7d61389b50fd5564d58657c388

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-foreach                  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-foreach
  run:
    - r-base
    - r-foreach

test:
  commands:
    - $R -e "library('TSP')"           # [not win]
    - "\"%R%\" -e \"library('TSP')\""  # [win]

about:
  home: https://github.com/mhahsler/TSP
  license: GPL-3.0-only
  summary: Basic infrastructure and some algorithms for the traveling salesperson problem (also traveling salesman problem; TSP). The package provides some simple algorithms and an interface to the Concorde TSP solver and its implementation of the Chained-Lin-Kernighan heuristic. The code for Concorde itself is not included
    in the package and has to be obtained separately.
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - conda-forge/r
