travis:
  secure:
    BINSTAR_TOKEN: kJARqiNnQCXJ3TiHVaSRUtbVrVxz2X0KkrOs+g7+RKwujKl6gLjRg9A7yI/rBgmN9anIXI6BkmFAtx9ZOPAGlSX4JxcyMYkuqhw+Pf4UBnXYMsI7OwO5U2mt7iEae8KvtXbw6OMOgM9BKpPoU+fVJpACEt7OfLCVFRxZhYvjmiWSgDxs3fVfp0M66u3S1aYUk+weVFW1FuEh+Ku9Bh378b2/WB/rgnEA0FpTicEdtkgAsl/l5usjeXv1/e3TE8MFesAArXFQ6pdGJd4IfldhUbDtCOjdTxcZa0t85Z06u86RQQkq1sOtaFy85wVnMs0EXHRrFf94mrSZS1NkuONoXor/prVTfmIIx4LBC6k3mJe/C8X4QxY0ZUKPCU4pK4StpSVs/PvCBAeXoRqx9WLkKYTJyFD08vxQG+qiXr6GcA3zA3zvsxVDnLV1VPQcybbm4soAFHUkhzqoGnp6bsz69uSgrYPClG45qWyN0iek9CLPL8yQGGPkp2gzwj2BUQ2TiqXzVAN7qKxldl+VlNcN/V8b7Ctr0MMINbekmplWQD7TCPUY3iZJCZ+GnEU3LQip1SA9IZzDRM2WBN2vJ6wGm+/9yXHTfMewcH9WT5Khx19LH3mE6ttfu5nAYCkHpn2439sdLYF5LPU2ec2Db7oRg5qAaYP2QRNnk1CYqD8+Eog=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
