appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: krRWzBRoPhGiYjaPkVK1QoanUS2nn4GN6+q+mZVOdxfKHS1cN++7TH347uVdcRrycuE8nBFa+YeEmEUTEBSngX2qK1gxyWSfQtYO5+gVLYaWD/b5la02AirpZTSuIYw4srq/lQ4W37wkWpN7xsWQkrcu31zCxeyTXEhA5WOcZyFedReHFlakT05S9Wl297iEWQM61E9hOun3kzLqGCF2dmj+jwNYeR1/qvW8IFBNqv4SeRZdtAGLgA7UsC+uWh7NShSQjSaac53n7jlpX22pF0K4Jn/gsgeiIK2CYeA7vtoqmuGnZxP8awqG20323ErrVXu7mb59yc0Gi+5pdM2s1A4x4ZwsfAtEWBuAMo1RFUnVbVx3rQWrXFfVaqrv6jR+t8M2QfGVfNsvIK/2qgIXDNXswCp5xjkUtIn/WZly2YGoHAy17oD14wJI1j5L9wgmLqCYwVD/+WP/2WUxqJSGTlLO3GhsPf99aLfIB1gFtSslaNfxhEKNpFUjfp2DKuYQy+IxYjcl3aea2jYp/FLhDxXNhcEboqJGQwI43/yDopyvYxb5QfigPKB9MtFcokqlLoY3jXYvvuhbBh0P/vcwmyziqo7bx/LhZiCz6odtSdDTH5egopMCC0k/oGQ3ql+hFxHFOByresPSvceW/xV4h+UMF2LES+/rWXxrweaLkro=}
